"""
LocalScript MCP Server.

Exposes the multi-agent Lua pipeline as MCP tools and resources.
Run with:
    python mcp_server/server.py
    # or via MCP inspector:
    mcp dev mcp_server/server.py

Part A — LocalScript AS an MCP server (other AI clients call us):
    Tools:  generate_lua, validate_lua, review_lua, fix_lua
    Resources: sessions list, session status, final.lua content

Part B — LocalScript USES external MCP tools:
    Agents can call external MCP tools (file_read, web_search, etc.)
    via the MCP client integrated into the pipeline.
"""

from __future__ import annotations

import asyncio
import logging
import sys
import tempfile
from datetime import datetime
from pathlib import Path

# Ensure project root is on sys.path
_PROJECT_ROOT = str(Path(__file__).resolve().parent.parent)
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

# Load .env early
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

from mcp.server.fastmcp import FastMCP

# ── Logging (stderr only — stdout is reserved for MCP protocol) ───────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-7s | %(name)s | %(message)s",
    stream=sys.stderr,
)
logger = logging.getLogger("localscript.mcp")

# ── FastMCP instance ──────────────────────────────────────────────────────────
mcp = FastMCP("LocalScript")

# ── Helpers ───────────────────────────────────────────────────────────────────

def _get_workspace() -> Path:
    from config.loader import load_settings
    settings = load_settings()
    return Path(settings["workspace"]["base_dir"])


def _make_session_dir() -> tuple[str, Path]:
    """Create a timestamped session directory."""
    workspace = _get_workspace()
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    session_id = f"session_{timestamp}"
    session_path = workspace / session_id
    session_path.mkdir(parents=True, exist_ok=True)
    return session_id, session_path


def _run_pipeline_sync(task: str, session_dir: str, max_iterations: int = 3) -> dict:
    """Run the LangGraph pipeline synchronously."""
    from graph.pipeline import run_pipeline
    return run_pipeline(task=task, session_dir=session_dir, max_iterations=max_iterations)


# ══════════════════════════════════════════════════════════════════════════════
#  PART A: LocalScript AS MCP Server — Tools
# ══════════════════════════════════════════════════════════════════════════════

@mcp.tool()
async def generate_lua(task: str, max_iterations: int = 3) -> str:
    """Generate validated Lua code using the multi-agent pipeline (Generator → Validator → Reviewer).

    The code goes through multiple agents:
    1. Generator writes Lua code based on the task description
    2. Validator compiles and executes it with luac/lua
    3. Reviewer checks code quality and correctness

    If validation fails, the pipeline retries up to max_iterations times.

    Args:
        task: Description of what the Lua code should do (e.g. "fibonacci with memoization")
        max_iterations: Maximum retry attempts if validation fails (default: 3)

    Returns:
        Generated Lua code if successful, or error description if failed.
    """
    logger.info("generate_lua: task=%s, max_iter=%d", task[:80], max_iterations)

    session_id, session_path = _make_session_dir()
    (session_path / "task.txt").write_text(task, encoding="utf-8")

    loop = asyncio.get_running_loop()
    try:
        final_state = await loop.run_in_executor(
            None,
            lambda: _run_pipeline_sync(task, str(session_path), max_iterations),
        )
    except Exception as e:
        logger.exception("Pipeline error")
        return f"ERROR: Pipeline failed — {e}"

    status = final_state.get("status", "failed")
    code = final_state.get("code", "")
    iterations = final_state.get("iterations", 0)

    if status == "done" and code:
        logger.info("generate_lua: SUCCESS in %d iteration(s), session=%s", iterations, session_id)
        return f"-- Generated by LocalScript ({iterations} iteration(s), session: {session_id})\n\n{code}"
    else:
        errors = final_state.get("errors", "Unknown error")
        return f"FAILED after {iterations} iteration(s).\nSession: {session_id}\nErrors: {errors}\nPartial code:\n{code or '(none)'}"


@mcp.tool()
async def validate_lua(code: str) -> str:
    """Validate Lua code by compiling with luac and executing with lua.

    Does NOT generate code — only checks existing code for syntax and runtime errors.

    Args:
        code: Lua source code to validate.

    Returns:
        "VALID" with stdout if code runs successfully, or error details if it fails.
    """
    logger.info("validate_lua: %d chars", len(code))

    from tools.lua_runner import LuaRunner

    with tempfile.TemporaryDirectory() as tmpdir:
        runner = LuaRunner(tmpdir)
        result = runner.execute(code, iteration=1)

    if result.success:
        output = result.stdout.strip()
        return f"VALID\n{f'Output: {output}' if output else '(no output)'}"
    else:
        return f"INVALID\nErrors: {result.errors}"


@mcp.tool()
async def review_lua(code: str, task: str = "") -> str:
    """Review Lua code quality using the Reviewer AI agent.

    Checks correctness, Lua idioms, error handling, and readability.
    Does NOT modify the code — only provides feedback.

    Args:
        code: Lua source code to review.
        task: Optional task description for context (what the code should do).

    Returns:
        Review feedback from the AI reviewer agent.
    """
    logger.info("review_lua: %d chars, task=%s", len(code), task[:50])

    from llm.factory import get_llm
    from agents.reviewer import ReviewerAgent

    loop = asyncio.get_running_loop()
    llm = get_llm("reviewer")
    agent = ReviewerAgent(llm)

    is_done, feedback = await loop.run_in_executor(
        None,
        lambda: agent.review(code=code, task=task),
    )

    status = "APPROVED" if is_done else "NEEDS IMPROVEMENT"
    return f"{status}\n\n{feedback}"


@mcp.tool()
async def fix_lua(code: str, errors: str, task: str = "") -> str:
    """Fix broken Lua code given the error messages.

    Takes existing code and its error output, returns corrected code.

    Args:
        code: Broken Lua source code.
        errors: Error messages from luac/lua or description of what's wrong.
        task: Optional task description for context.

    Returns:
        Fixed Lua source code.
    """
    logger.info("fix_lua: %d chars code, %d chars errors", len(code), len(errors))

    from llm.factory import get_llm
    from agents.generator import GeneratorAgent

    loop = asyncio.get_running_loop()
    llm = get_llm("generator")
    agent = GeneratorAgent(llm)

    fixed_code = await loop.run_in_executor(
        None,
        lambda: agent.generate(task=task or "Fix the Lua code", errors=errors),
    )

    return fixed_code


# ══════════════════════════════════════════════════════════════════════════════
#  PART A: LocalScript AS MCP Server — Resources
# ══════════════════════════════════════════════════════════════════════════════

@mcp.resource("sessions://list")
async def list_sessions() -> str:
    """List all LocalScript workspace sessions with their status."""
    workspace = _get_workspace()
    if not workspace.exists():
        return "No sessions found."

    lines = []
    for entry in sorted(workspace.iterdir(), reverse=True):
        if not entry.is_dir() or not entry.name.startswith("session_"):
            continue
        task_file = entry / "task.txt"
        task = task_file.read_text(encoding="utf-8").strip() if task_file.exists() else "(no task)"
        has_final = (entry / "final.lua").exists()
        status = "✓ done" if has_final else "⏳ pending"
        lines.append(f"{entry.name}  [{status}]  {task[:60]}")

    return "\n".join(lines) if lines else "No sessions found."


@mcp.resource("session://{session_id}/status")
async def get_session_status(session_id: str) -> str:
    """Get detailed status of a specific session."""
    session_path = _get_workspace() / session_id
    if not session_path.is_dir():
        return f"Session '{session_id}' not found."

    task_file = session_path / "task.txt"
    task = task_file.read_text(encoding="utf-8").strip() if task_file.exists() else "(no task)"
    iterations = len(list(session_path.glob("iteration_*.lua")))
    has_final = (session_path / "final.lua").exists()

    # Collect error files
    error_files = sorted(session_path.glob("iteration_*_errors.txt"))
    last_error = ""
    if error_files:
        last_error = error_files[-1].read_text(encoding="utf-8").strip()

    report = session_path / "report.md"
    report_text = report.read_text(encoding="utf-8") if report.exists() else ""

    return f"""Session: {session_id}
Task: {task}
Iterations: {iterations}
Final: {'available' if has_final else 'not yet'}
Last error: {last_error or '(none)'}

{report_text}"""


@mcp.resource("session://{session_id}/final.lua")
async def get_final_lua(session_id: str) -> str:
    """Get the final generated Lua code from a session."""
    final_path = _get_workspace() / session_id / "final.lua"
    if not final_path.exists():
        return f"No final.lua found for session '{session_id}'. Pipeline may still be running or failed."
    return final_path.read_text(encoding="utf-8")


# ══════════════════════════════════════════════════════════════════════════════
#  PART B: MCP Client — LocalScript USES external MCP tools
# ══════════════════════════════════════════════════════════════════════════════

# External MCP tools are configured in config/settings.yaml under `mcp_tools:`.
# The pipeline agents can call these tools during generation.
# This is implemented as a LangChain tool wrapper that connects to external MCP servers.

async def _get_external_mcp_tools() -> list:
    """
    Load external MCP tool configurations from settings.yaml.
    Returns LangChain-compatible tool wrappers for each configured MCP server.

    Config example in settings.yaml:
        mcp_tools:
          - name: filesystem
            command: npx
            args: ["-y", "@modelcontextprotocol/server-filesystem", "/path/to/dir"]
          - name: web_search
            command: npx
            args: ["-y", "@anthropic/mcp-server-brave-search"]
            env:
              BRAVE_API_KEY: "..."
    """
    from config.loader import load_settings
    settings = load_settings()
    mcp_configs = settings.get("mcp_tools", [])

    if not mcp_configs:
        return []

    tools = []
    for cfg in mcp_configs:
        try:
            tool = await _connect_mcp_tool(cfg)
            if tool:
                tools.extend(tool)
                logger.info("Loaded MCP tools from: %s", cfg.get("name", "unknown"))
        except Exception as e:
            logger.warning("Failed to load MCP tool '%s': %s", cfg.get("name", "?"), e)

    return tools


async def _connect_mcp_tool(config: dict) -> list | None:
    """Connect to a single external MCP server and return its tools as LangChain tools."""
    try:
        from mcp import ClientSession, StdioServerParameters
        from mcp.client.stdio import stdio_client
    except ImportError:
        logger.warning("MCP client SDK not available — install with: pip install 'mcp[cli]'")
        return None

    name = config.get("name", "unknown")
    command = config["command"]
    args = config.get("args", [])
    env = config.get("env", {})

    server_params = StdioServerParameters(command=command, args=args, env=env)

    async with stdio_client(server_params) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()
            mcp_tools = await session.list_tools()

            # Convert MCP tools to simple callable wrappers
            langchain_tools = []
            for tool in mcp_tools.tools:
                langchain_tools.append(_make_langchain_tool(name, tool, session))

            return langchain_tools


def _make_langchain_tool(server_name: str, mcp_tool, session):
    """Wrap an MCP tool as a simple callable for use in agents."""
    from langchain_core.tools import StructuredTool

    async def _call(**kwargs):
        result = await session.call_tool(mcp_tool.name, arguments=kwargs)
        return result.content[0].text if result.content else ""

    return StructuredTool.from_function(
        func=lambda **kw: asyncio.run(_call(**kw)),
        name=f"{server_name}__{mcp_tool.name}",
        description=mcp_tool.description or f"MCP tool: {mcp_tool.name}",
    )


# ══════════════════════════════════════════════════════════════════════════════
#  Entry point
# ══════════════════════════════════════════════════════════════════════════════

def main():
    """Run the MCP server via stdio transport."""
    logger.info("Starting LocalScript MCP Server...")
    mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
