"""
Validator Agent — runs luac + lua, explains errors if any.
This is what makes LocalScript different from ChatDev: real code execution.

NEW: Functional test generation as required by Aleksandr Bordash:
"Надо написать test case, который скажет: вот у email такой-то, вот это email или нет"

TOLERANT MODE: Accepts code if it runs successfully, even if some tests fail.
Tests generated by 7B models may contain errors, but the code itself can be valid.
"""

from agents.base import BaseAgent
from tools.lua_runner import LuaRunner, LuaResult
from langchain_core.language_models import BaseChatModel
import logging
import os

logger = logging.getLogger("localscript.agents")


class ValidatorAgent(BaseAgent):
    def __init__(self, llm: BaseChatModel, runner: LuaRunner):
        super().__init__("validator", llm)
        self.runner = runner
        self._last_result: LuaResult | None = None  # Store last execution result

    def validate(self, code: str, task: str, iteration: int) -> tuple[bool, str]:
        """
        Run luac + lua. If errors, use LLM to explain them clearly.
        Returns: (is_valid, error_explanation_or_empty)
        """
        logger.info(f"[Validator] Starting validation (iteration {iteration}, code: {len(code)} chars)")

        result: LuaResult = self.runner.execute(code, iteration)
        self._last_result = result  # Save for profiling metrics

        if result.success:
            logger.info(f"[Validator] ✓ Code validated successfully (execution time: {result.execution_time:.2f}s)")
            return True, ""

        logger.warning(f"[Validator] ✗ Validation failed: {result.errors[:100]}...")
        logger.info("[Validator] Generating error explanation via LLM...")

        # Use LLM to explain errors (like ChatDev's Programmer Test Error Summary)
        explanation = self.invoke(
            f"Task: {task}\n\nLua code:\n{code}\n\nError output:\n{result.errors}\n\nExplain what is wrong:"
        )

        logger.info(f"[Validator] Error explanation generated ({len(explanation)} chars)")
        return False, explanation

    def validate_with_tests(self, code: str, test_code: str, task: str, iteration: int) -> tuple[bool, str, dict]:
        """
        Run code with functional test cases.
        Returns: (is_valid, error_explanation_or_empty, test_results)

        test_results = {
            "total": int,
            "passed": int,
            "failed": int,
            "details": str  # Output from test execution
        }
        """
        # IMPORTANT: Remove trailing return statement from code before adding tests
        # Generator often adds "return wf.vars.xxx" at the end, which makes tests unreachable
        code_lines = code.strip().split('\n')
        trailing_return = None

        # Check if last non-empty line is a return statement
        for i in range(len(code_lines) - 1, -1, -1):
            line = code_lines[i].strip()
            if line:  # Found last non-empty line
                if line.startswith('return '):
                    trailing_return = line
                    code_lines = code_lines[:i]  # Remove this line
                break

        # Reconstruct code without trailing return
        code_without_return = '\n'.join(code_lines)

        # Special case: if code is just a return statement, skip tests
        # Tests expect functions, but simple returns don't need testing
        if not code_without_return.strip():
            # Code is just "return something" - execute directly without tests
            logger.info("[Validator] Simple return statement detected, skipping tests")
            result: LuaResult = self.runner.execute(code, iteration)
            self._last_result = result

            if result.success:
                logger.info(f"[Validator] ✓ Code executed successfully (no tests)")
                return True, "", {
                    "total": 0,
                    "passed": 0,
                    "failed": 0,
                    "details": "Simple return statement, no tests generated"
                }
            else:
                logger.warning(f"[Validator] ✗ Execution failed: {result.stderr}")
                return False, result.stderr, {
                    "total": 0,
                    "passed": 0,
                    "failed": 0,
                    "details": result.stderr
                }

        # Combine: code (without return) + tests + return (if existed)
        combined_parts = []
        if code_without_return.strip():  # Only add if not empty
            combined_parts.append(code_without_return)
        combined_parts.append("\n-- ═══ Functional Tests ═══")
        combined_parts.append(test_code)
        if trailing_return:
            combined_parts.append(f"\n-- Return result for LowCode\n{trailing_return}")

        combined_code = '\n'.join(combined_parts)

        result: LuaResult = self.runner.execute(combined_code, iteration)
        self._last_result = result

        # Parse test results from output
        test_results = self._parse_test_results(result)

        # Get test pass threshold from environment (default: 0.5 = 50%)
        threshold = float(os.getenv("TEST_PASS_THRESHOLD", "0.5"))

        # TOLERANT MODE: Accept if code runs successfully, even if some tests fail
        # Tests might be incorrect (generated by 7B model), but code itself is valid
        if result.success:
            # Calculate pass rate
            pass_rate = test_results["passed"] / test_results["total"] if test_results["total"] > 0 else 0

            if test_results["failed"] == 0:
                # Perfect: all tests passed
                logger.info(f"[Validator] ✓ All {test_results['total']} tests passed")
                return True, "", test_results
            elif pass_rate >= threshold:
                # Good enough: meets threshold, code runs without errors
                logger.info(f"[Validator] ✓ Code valid despite {test_results['failed']} test failures (pass rate: {pass_rate:.1%}, threshold: {threshold:.1%})")
                return True, "", test_results
            else:
                # Too many test failures
                logger.warning(f"[Validator] ✗ Pass rate {pass_rate:.1%} below threshold {threshold:.1%}")
            # Continue to generate explanation

        # Generate explanation for failures
        if test_results["failed"] > 0:
            explanation = self.invoke(
                f"Task: {task}\n\nCode:\n{code}\n\nTests:\n{test_code}\n\n"
                f"Test results: {test_results['passed']}/{test_results['total']} passed\n\n"
                f"Output:\n{result.stdout}\n{result.stderr}\n\n"
                f"Explain what failed and why:"
            )
        else:
            explanation = self.invoke(
                f"Task: {task}\n\nCode:\n{code}\n\nError:\n{result.errors}\n\nExplain what is wrong:"
            )

        return False, explanation, test_results

    def _parse_test_results(self, result: LuaResult) -> dict:
        """
        Parse test results from Lua assert() output.

        Lua assert() failures look like:
        lua: file.lua:10: assertion failed!
        or
        lua: file.lua:10: Should accept valid email
        """
        import re

        output = result.stdout + "\n" + result.stderr

        # Count assertions in output
        # Successful asserts produce no output
        # Failed asserts produce error messages

        # Look for assertion failures
        assertion_failures = re.findall(r'assertion failed|lua:.*:\d+:', output)
        failed_count = len(assertion_failures)

        # Estimate total tests (this is approximate)
        # We'll count "Test" comments in the output or assume from failures
        test_comments = re.findall(r'-- Test \d+:', output)
        total_tests = max(len(test_comments), failed_count)

        # If no failures and code succeeded, assume all tests passed
        if result.success and failed_count == 0:
            # Try to count test cases from the output
            # Look for successful test indicators
            total_tests = max(total_tests, 1)  # At least 1 test if code ran

        passed_count = total_tests - failed_count

        return {
            "total": total_tests,
            "passed": passed_count,
            "failed": failed_count,
            "details": output
        }

